/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChainWatcherRouteImport } from './routes/chain-watcher'
import { Route as AttackHistoryRouteImport } from './routes/attack-history'
import { Route as IndexRouteImport } from './routes/index'

const ChainWatcherRoute = ChainWatcherRouteImport.update({
  id: '/chain-watcher',
  path: '/chain-watcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackHistoryRoute = AttackHistoryRouteImport.update({
  id: '/attack-history',
  path: '/attack-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack-history': typeof AttackHistoryRoute
  '/chain-watcher': typeof ChainWatcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack-history': typeof AttackHistoryRoute
  '/chain-watcher': typeof ChainWatcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attack-history': typeof AttackHistoryRoute
  '/chain-watcher': typeof ChainWatcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attack-history' | '/chain-watcher'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attack-history' | '/chain-watcher'
  id: '__root__' | '/' | '/attack-history' | '/chain-watcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackHistoryRoute: typeof AttackHistoryRoute
  ChainWatcherRoute: typeof ChainWatcherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chain-watcher': {
      id: '/chain-watcher'
      path: '/chain-watcher'
      fullPath: '/chain-watcher'
      preLoaderRoute: typeof ChainWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-history': {
      id: '/attack-history'
      path: '/attack-history'
      fullPath: '/attack-history'
      preLoaderRoute: typeof AttackHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackHistoryRoute: AttackHistoryRoute,
  ChainWatcherRoute: ChainWatcherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
